services:
  - type: web
    name: portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app.controllers:create_app()"
    envVars:
      - key: SECRET_KEY
        generateValue: true