services:
  - type: web
    name: portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_CONFIG
        value: config.ProductionConfig